#!/usr/bin/env python3
"""Regenerate docs/PROMPTS.md from the recorder scripts.

The prompts that produced the recordings live in slides/tools/record_*.sh,
because that is what actually ran. Copying them into prose by hand would let
the two drift, and a prompt list that no longer matches the recording is worse
than none — so the document is generated and CI asserts it is current:

    python3 scripts/extract_prompts.py --check

Usage:
    python3 scripts/extract_prompts.py            # rewrite docs/PROMPTS.md
    python3 scripts/extract_prompts.py --check    # exit 1 if it is stale
"""
from __future__ import annotations

import re
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "PROMPTS.md"

RECORDERS = [
    ("walk", ROOT / "slides" / "tools" / "record_walkthrough.sh"),
    ("talk", ROOT / "slides" / "tools" / "record_talk.sh"),
]


def logical_lines(text: str) -> list[str]:
    """Join bash backslash-continuations into one line each."""
    out, buf = [], ""
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.endswith("\\"):
            buf += line[:-1].strip() + " "
            continue
        out.append((buf + line.strip()).strip())
        buf = ""
    if buf:
        out.append(buf.strip())
    return out


def parse(path: Path) -> list[dict]:
    """Pull the ordered run_slides / run_shell / run_turn steps out of a recorder."""
    steps: list[dict] = []
    for line in logical_lines(path.read_text()):
        verb = line.split(" ", 1)[0] if line else ""
        if verb not in ("run_slides", "run_shell", "run_turn"):
            continue
        # Skip the function definitions themselves.
        if "()" in line.split("#")[0]:
            continue
        try:
            argv = shlex.split(line, comments=True)
        except ValueError:
            continue
        if verb == "run_slides" and len(argv) >= 5:
            steps.append({"kind": "slide", "id": argv[1], "title": argv[2],
                          "deck": argv[3], "pages": argv[4]})
        elif verb == "run_shell" and len(argv) >= 3:
            steps.append({"kind": "shell", "label": argv[1], "cmds": argv[2:]})
        elif verb == "run_turn" and len(argv) >= 3:
            steps.append({"kind": "prompt", "label": argv[1], "text": argv[2]})
    return steps


def working_rules(path: Path) -> str:
    """The CLAUDE.md the recorder writes into the sandbox before it starts.

    Reproducing the prompts without reproducing these is not the same run:
    they are what keeps the answers short enough to project and stop the
    agent reaching for libraries the venv does not have.
    """
    text = path.read_text()
    start = text.find('cat > "$D/CLAUDE.md" <<EOF')
    if start == -1:
        return ""
    body = text[text.index("\n", start) + 1:]
    body = body[: body.index("\nEOF")]
    # $HERE/../ is the repo root as the recorder sees it; spell it out, because
    # a reader pasting this into a scratch directory has no such relative path.
    return (body.replace("\\`", "`").replace("${COLS}", "105")
            .replace("$HERE/../", "/path/to/IMBrave150-mock/"))


def render(name: str, steps: list[dict]) -> list[str]:
    lines: list[str] = []
    n = 0
    for s in steps:
        if s["kind"] == "slide":
            lines.append(f"\n### Slide break — {s['title']}\n")
            lines.append(
                f"`presenterm --present slides/{name_dir(name)}/{s['deck']}` "
                f"— {s['pages']} page(s). Nothing is asked of the agent here; "
                f"this is where the presenter talks.\n"
            )
        elif s["kind"] == "shell":
            lines.append(f"\n**At the shell** ({s['label']}):\n")
            lines.append("```bash")
            lines.extend(s["cmds"])
            lines.append("```\n")
        else:
            n += 1
            lines.append(f"\n**Prompt {n}** · *{s['label']}*\n")
            lines.append("```text")
            lines.append(s["text"])
            lines.append("```\n")
    return lines


def name_dir(name: str) -> str:
    return "walkthrough" if name == "walk" else "talk"


def count_prompts(steps: list[dict]) -> int:
    return sum(1 for s in steps if s["kind"] == "prompt")


HEADER = """<!-- GENERATED by scripts/extract_prompts.py — do not edit by hand.
     The prompts below are read out of slides/tools/record_*.sh, which is what
     actually ran. Edit those, then regenerate. -->

# The prompt list

Everything in this repository — the pooled cohort, the matched analysis, the
figures, the manuscript — was produced by asking an agent in ordinary
sentences. This file is that list of sentences, verbatim, in order.

Nothing here is a magic incantation. They are the questions a colleague would
ask, which is the point of the exercise; the work is in reading what comes back.

> ⚠️ **You will not get identical numbers.** An agent writes its own scripts,
> and two runs make different reasonable choices (which covariates, which
> caliper, ascending or descending). The published result is stable to about
> ±0.05 on the hazard ratio; see [`live-demo/reference-run/`](../live-demo/reference-run/)
> for what one full run produced and [`PIPELINE.md`](PIPELINE.md) for the
> ranges the acceptance checks allow.

## Three ways to run it

| Route | What you type | Time | Pace |
|---|---|---|---|
| **A · guided** | one sentence, then `next` 32 times | 60–100 min | You stop between every step. Acceptance checks after each. |
| **B · walkthrough** | the {n_walk} prompts below | ~35 min | The shape of the work, start to finish, no methodology arguments. |
| **C · long** | the {n_talk} prompts below | ~65 min | The same study with the arguments kept in. |

Route A is the one to use if you want to *learn* it; B and C are what the
recordings show. All three end in a manuscript whose every number came out of
a file on disk.
"""

ROUTE_A = """
---

## Route A — guided, one mission at a time

Open this repository in Claude Code (or any agent that can read files and run
Python) and say:

```text
follow the ./live-demo mission by mission
```

That is the entire input. The agent reads [`live-demo/README.md`](../live-demo/README.md),
executes Mission 0.1, runs its acceptance script, summarises what it found, and
stops. You then drive it with four words:

| You say | It does |
|---|---|
| `next` | the next mission |
| `skip` | skips, and tells you what downstream missions that breaks |
| `why` | explains the *methodological reason* for the step, without advancing |
| `?` | re-explains *what just happened*, in plain language, without advancing |

Nine chapters, 32 missions, from ten raw hospital CSVs to a typeset preprint.
Each mission declares its output filenames, and
[`live-demo/verify/`](../live-demo/verify/) checks them against hard numbers —
so a run that quietly went wrong fails loudly instead of producing a
confident-looking manuscript.

```bash
cd live-demo && ../.venv/bin/python verify/run_all.py   # check a finished run
```

Before running it in front of anyone:

```bash
cd live-demo && ../.venv/bin/python verify/preflight.py --full
```
"""

SANDBOX_TMPL = """
---

## Routes B and C — the recorded sessions

Both recordings ran in a scratch directory containing **only the raw inputs**:
the ten hospital CSVs and the site catalogue. No scripts, no notes, no
reference solutions. The agent wrote every line of analysis code during the
session.

```bash
mkdir -p /tmp/run && cd /tmp/run
cp -R /path/to/IMBrave150-mock/hospitals .
cp /path/to/IMBrave150-mock/hospitals_meta.csv .
```

and a `CLAUDE.md` in that directory holding the working rules — narrow output
so it projects, no libraries the environment does not have:

```markdown
{rules}
```

Then start the agent and paste the prompts below one at a time, waiting for
each to finish. To reproduce the recording itself, including the slide breaks
and the chapter markers, run the recorder instead:

```bash
slides/tools/record_walkthrough.sh    # route B  → slides/cast/walk.cast
slides/tools/record_talk.sh           # route C  → slides/cast/talk-full.cast
```

It needs `tmux`, `asciinema`, `presenterm` and `bat`, and it drives a real
nested agent session — expect it to take as long as the recording.
"""

FOOTER = """
---

## Reading the answers back

The prompts are the easy half. What makes the result trustworthy is what you
do with each reply, and it is the same four habits every time:

1. **Ask for the plan before the run.** Several prompts above say *"tell me
   why you chose it before you run it"*. A method you agreed to in advance is
   one you can defend; a method you found in the output is one you are stuck
   with.
2. **Make it name its sources.** *"Every number must come from a file on disk,
   and mark which file each one came from."* This is what makes the audit in
   the next step possible at all.
3. **Ask it to check its own work against the files.** Each route closes on
   this, and in the recorded runs it found real defects — an unsourced number,
   a claim the data did not support, a script that was not idempotent.
4. **Run the acceptance checks anyway.** `live-demo/verify/` does not care what
   the agent said it did.

See [`PIPELINE.md`](PIPELINE.md) for what each step consumes and produces, and
[`FILE-TREE.md`](FILE-TREE.md) for where everything lands.
"""


def build() -> str:
    parsed = {name: parse(path) for name, path in RECORDERS}
    rules = working_rules(RECORDERS[0][1]).strip()

    out = [HEADER.format(n_walk=count_prompts(parsed['walk']),
                         n_talk=count_prompts(parsed['talk'])), ROUTE_A, SANDBOX_TMPL.format(rules=rules)]

    titles = {
        "walk": ("Route B — the walkthrough",
                 "The ordinary shape of a study: data, cleaning, exploring, "
                 "analysis, writing. Recorded as "
                 "[`slides/cast/walk.cast`](../slides/cast/walk.cast) "
                 "(33 min) and playable at "
                 "<https://imbrave150-talk.pages.dev/talk>."),
        "talk": ("Route C — the long version",
                 "The same study with the methodology kept in: an ambiguous "
                 "prompt that moves the answer, 120 analytic paths, four "
                 "independent reviewers. Recorded as "
                 "[`slides/cast/talk-full.cast`](../slides/cast/talk-full.cast) "
                 "(64 min) and playable at "
                 "<https://imbrave150-talk.pages.dev/talk-long>."),
    }

    for name, path in RECORDERS:
        steps = parsed[name]
        title, blurb = titles[name]
        rel = f"slides/tools/{path.name}"
        out.append(f"\n---\n\n## {title}\n")
        out.append(f"{blurb}\n")
        out.append(f"**{count_prompts(steps)} prompts.** "
                   f"Source: [`{rel}`](../{rel})\n")
        out.extend(render(name, steps))

    out.append(FOOTER)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip() + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale — run "
                  f"python3 scripts/extract_prompts.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    n = sum(count_prompts(parse(p)) for _, p in RECORDERS)
    print(f"wrote {OUT.relative_to(ROOT)} — {n} prompts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
